### ISSUE TITLE
Responsiveness on 'You're Going' 

### ISSUE THREAD

**Issue by vs77bb** [anggxyz/convo-app#154]
When I scrunch up a window, 'You're Going' starts to overlap with the events 

<img width="261" alt="image" src="https://github.com/anggxyz/convo-app/assets/23297747/7a3d903f-cf63-4648-8565-b723a415d042">

**Comment by anggxyz** [comment]
replaced "you're going" with an icon and hover tooltip
<img width="158" alt="image" src="https://github.com/anggxyz/convo-app/assets/10832414/0de1f34c-50d9-4e68-9b71-1d68ceb56aa4">
