### ISSUE TITLE
Clearer Visual Distinction Between Past Events / Upcoming Events in Convo Series 

### ISSUE THREAD

**Issue by vs77bb** [anggxyz/convo-app#157]
Same screenshot. It'd be nice to have a cleaner distinction between past events and future events. 

I am posting this issue January 30th, at 8:33AM local time.

![image](https://github.com/anggxyz/convo-app/assets/23297747/45e056a7-4701-4b0c-b439-fbccd6409ed6)

At first glance it seems out of order, but I realize it's just moving the old events to the bottom. 

Not quite sure what is best case scenario here, but think there could be improvement in showing past events. 

We also are 30 minutes past the Jan 30th event (so it is a past event now), but it doesn't show an 'X' by it. Maybe that will change in the next few hours? It would be nice to show an 'X' by an event right at it's start time, I think.

**Comment by anggxyz** [comment]
<img width="445" alt="image" src="https://github.com/anggxyz/convo-app/assets/10832414/c2e5bb1f-6bd2-4173-b835-52727fd45b12">
what do you think?
